"""added race column

Revision ID: 1bcb84350097
Revises: fbbbada3743d
Create Date: 2026-06-27 19:30:51.501926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bcb84350097'
down_revision: Union[str, Sequence[str], None] = 'fbbbada3743d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Person', sa.Column('race', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Person', 'race')
    # ### end Alembic commands ###
