"""added another column

Revision ID: d9bfe9845003
Revises: ba654bdafcae
Create Date: 2026-06-27 14:29:36.541653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9bfe9845003'
down_revision: Union[str, Sequence[str], None] = 'ba654bdafcae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Person', sa.Column('alembic_test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Person', 'alembic_test')
    # ### end Alembic commands ###
