"""added foreign key

Revision ID: ddd098534a91
Revises: 1bcb84350097
Create Date: 2026-06-27 19:42:59.288216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd098534a91'
down_revision: Union[str, Sequence[str], None] = '1bcb84350097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Dog', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Dog', 'Person', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Dog', type_='foreignkey')
    op.drop_column('Dog', 'owner_id')
    # ### end Alembic commands ###
