"""added new column on Dog

Revision ID: fbbbada3743d
Revises: d9bfe9845003
Create Date: 2026-06-27 14:37:40.277061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbbbada3743d'
down_revision: Union[str, Sequence[str], None] = 'd9bfe9845003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Dog', sa.Column('alembic_test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Dog', 'alembic_test')
    # ### end Alembic commands ###
